// <auto-generated />
namespace school_adar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Update_register_model : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_register_model));
        
        string IMigrationMetadata.Id
        {
            get { return "202201231134292_Update_register_model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
